name: dockerhub-readme-ci

on:
  push:
    branches:
      - "master"
    paths:
#     For GitHub Action
      - ".github/workflows/dockerhub-readme-ci.yml"
#     For the README file for the Docker Hub
      - "README_DOCKERHUB.md"

  # For debug and test only
  pull_request:
    branches:
      - "master"
    paths:
#     For GitHub Action
      - ".github/workflows/docker-update-readme.yml"
#     For the README file for the Docker Hub
      - "README_DOCKERHUB.md"

env:
  # Optional short description shown on Docker Hub
  DOCKER_IMAGE_NAME: slack-mcp-server
  DOCKER_HUB_SHORT_DESCRIPTION: 🦾 A strong MCP server for Slack.

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Update repo description in Docker Hub
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Set your Docker Hub repository in the form <namespace>/<name>
          # If your Docker Hub repo name matches this GitHub repo name, this will work:
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}
          short-description: ${{ vars.DOCKER_HUB_SHORT_DESCRIPTION }}
          readme-filepath: ./README_DOCKERHUB.md
