name: dockerhub-readme-ci

on:
  push:
    branches:
      - "master"
    paths:
#     For GitHub Action
      - ".github/workflows/docker-update-readme.yml"
#     For the README file for the Docker Hub
      - "README_DOCKERHUB.md"

  # For debug and test only
#  pull_request:
#    branches:
#      - "master"
#    paths:
##     For GitHub Action
#      - ".github/workflows/docker-update-readme.yml"
##     For the README file for the Docker Hub
#      - "README_DOCKERHUB.md"

env:
  TEST_TAG: user/slack-mcp-server:test
  DOCKER_HUB_SHORT_DESCRIPTION: 🦾 A strong MCP server for Slack.

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update repo description in Docker Hub
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          short-description: ${{ env.DOCKER_HUB_SHORT_DESCRIPTION }}
          readme-filepath: ./README_DOCKERHUB.md
