name: dockerhub-readme-ci

on:
  push:
    branches:
      - "master"
    paths:
#     For GitHub Action
      - ".github/workflows/dockerhub-readme-ci.yml"
#     For the README file for the Docker Hub
      - "README_DOCKERHUB.md"

  # For debug and test only
#  pull_request:
#    branches:
#      - "master"
#    paths:
##     For GitHub Action
#      - ".github/workflows/dockerhub-readme-ci.yml"
##     For the README file for the Docker Hub
#      - "README_DOCKERHUB.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Change token
      - name: Get Docker Hub JWT
        env:
          U: chisanan232
          P: ${{ secrets.DOCKERHUB_README_UPDATE_TOKEN }}
        run: |
          set -euo pipefail
          JWT=$(curl -s -H 'Content-Type: application/json' \
            -d "{\"username\":\"${U}\",\"password\":\"${P}\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          test -n "$JWT" -a "$JWT" != null || (echo "JWT empty"; exit 1)
          echo "JWT=$JWT" >> $GITHUB_ENV
          echo "✅ Got JWT for user: $U"

      - name: Update the Docker Hub short description and overview
        env:
          REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}
          JWT:  ${{ env.JWT }}
        run: |
          set -euo pipefail
          ORIG=$(curl -s -H "Authorization: JWT $JWT" \
            "https://hub.docker.com/v2/repositories/${REPO}/" | jq -r .full_description)
          README_FILE="README_DOCKERHUB.md"
          # Read README and encode as a JSON string (preserves newlines/special chars)
          NEW=$(jq -Rs . < "$README_FILE")
          SHORT_NEW="${{ vars.DOCKER_HUB_SHORT_DESCRIPTION }}"

          CODE=$(curl -s -o /dev/null -w '%{http_code}' -X PATCH \
            -H "Authorization: JWT $JWT" -H "Content-Type: application/json" \
            -d "{\"description\":\"${SHORT_NEW}\", \"full_description\": ${NEW} }" \
            "https://hub.docker.com/v2/repositories/${REPO}/")
          echo "PATCH full_description -> $CODE"
          
          # Check if the response code is 200 (success)
          if [ "$CODE" != "200" ]; then
            echo "❌ Failed to update Docker Hub README. HTTP status code: $CODE"
            exit 1
          fi
          
          echo "✅ Successfully updated Docker Hub README"
