#################################################################################################################################
#
# Workflow Description:
#     Use Poetry to run testing by specific type with all test items via PyTest and generate its testing
#     coverage report (it would save reports by 'actions/upload-artifact').
#
# Workflow input parameters:
#     * test_type: The testing type. In generally, it only has 2 options: 'unit-test' and 'integration-test'.
#     * all_test_items_paths: The target paths of test items under test.
#     * setup_http_server: If it's true, it would set up and run HTTP server for testing.
#     * http_server_host: The host IPv4 address of HTTP server.
#     * http_server_port: The port number of HTTP server.
#     * http_server_app_module: The module path of HTTP server.
#     * http_server_enter_point: The object about the web application.
#
# Workflow running output:
#     No, but it would save the testing coverage reports to provide after-process to organize and record.
#
#     * Upload-Artifact:
#         * coverage: The test coverage report which be generated by PyTest, and it's recorded after run test done.
#                           The file name format would be .coverage.<test type>.<runtime os>-<python-version>
#
#################################################################################################################################

name: Run test items via PyTest

on:
  workflow_call:
    inputs:
      test_type:
        description: "The testing type. In generally, it only has 2 options: 'unit-test' and 'integration-test'."
        required: true
        type: string
      all_test_items_paths:
        description: "The target paths of test items under test."
        required: true
        type: string
      setup_http_server:
        description: "If it's true, it would set up and run HTTP server for testing."
        type: boolean
        required: false
        default: false
      http_server_host:
        description: "The host IPv4 address of HTTP server."
        type: string
        required: false
        default: 0.0.0.0
      http_server_port:
        description: "The port number of HTTP server."
        type: string
        required: false
        default: 12345
      http_server_app_module:
        description: "The module path of HTTP server."
        type: string
        required: false
        default: app
      http_server_enter_point:
        description: "The object about the web application."
        type: string
        required: false
        default: app

jobs:
  run_test_items:
    strategy:
      matrix:
        python-version: [3.9,'3.10','3.11','3.12','3.13']
        os: [ubuntu-latest,ubuntu-22.04,macos-latest,macos-14]
        test-path: ${{fromJson(inputs.all_test_items_paths)}}
      fail-fast: false    # Fix issue in GitHub Action: FailFast: cancelling since parallel instance has failed

    uses: Chisanan232/GitHub-Action_Reusable_Workflows-Python/.github/workflows/rw_poetry_run_test.yaml@v7.3
    with:
      runtime_os: ${{ matrix.os }}
      python_version: ${{ matrix.python-version }}
      test_type: ${{ inputs.test_type }}
      all_test_items_paths: ${{ inputs.all_test_items_paths }}
      setup_http_server: ${{ inputs.setup_http_server }}
      http_server_host: ${{ inputs.http_server_host }}
      http_server_port: ${{ inputs.http_server_port }}
      http_server_app_module: ${{ inputs.http_server_app_module }}
      http_server_enter_point: ${{ inputs.http_server_enter_point }}
