name: Validate Slack Event Types

on:
  schedule:
    # ── Every Saturday at 00:00 UTC ─────────────────────────────
    - cron: '0 0 * * 6'
  workflow_dispatch:       # optional manual trigger

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13

      - name: Activate the uv virtual environment
        run: |
          uv venv
          . .venv/bin/activate

      - name: Install all the project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Build Python runtime environment by UV with dependency group **
        run: |
          uv pip install .

      - name: Run Slack event-type validator
        run: |
          uv run python ./scripts/ci/validate_slack_event_types.py --validate --strict
